<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\PlayerRepository' shared autowired service.

return $this->privates['App\Repository\PlayerRepository'] = new \App\Repository\PlayerRepository(($this->privates['App\Repository\GameRepository'] ?? $this->load('getGameRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
