<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVNBvSgL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVNBvSgL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVNBvSgL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVNBvSgL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVNBvSgL\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'VNBvSgL',
    'container.build_id' => '00650ca2',
    'container.build_time' => 1563771009,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVNBvSgL');
