<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBvPZ3L6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBvPZ3L6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBvPZ3L6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBvPZ3L6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBvPZ3L6\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'BvPZ3L6',
    'container.build_id' => 'da9d2602',
    'container.build_time' => 1563821421,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBvPZ3L6');
